---
  - name: start-postfix
    service:
      name: postfix
      state: started

  - name: reload-postfix
    service:
      name: postfix
      state: reloaded

  - name: check-postfix
    command: /usr/sbin/postfix -c /etc/postfix check
